; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
;platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37
board = heltec_wifi_lora_32_V3
framework = arduino
board_build.partitions = partitions.csv

lib_deps =
    https://github.com/libdriver/sx1262#20beaef3ae258e96c7e028c2c677ba460d334ef3

; These build flags are already defined in "boards/dongles3.json"
; build_flags = 
;     -DARDUINO_USB_MODE=1
;     -DARDUINO_USB_CDC_ON_BOOT=1

; monitor_speed = 115200
; upload_port = /dev/ttyACM0
; upload_speed = 230400
